# Generated by Django 5.0.6 on 2025-06-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('git_url', models.URLField()),
                ('project_url', models.URLField()),
                ('note', models.TextField()),
                ('substance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
    ]
